<?php

$hoge = array("ALBURY","PENRITH","MANLY","QUEANBEYAN","CESSNOCK","WERRINGTON","RAYMOND TERRACE","NAREMBURN","TUNCURRY","REVESBY","CAMPSIE","KOGARAH","BURWOOD","STANHOPE GARDENS","BEGA","CHARLESTOWN","HURSTVILLE","MAROUBRA","ST MARYS","RYDE","CAMPBELLTOWN","SWANSEA","BAULKHAM HILLS","ENGADINE","ROCKDALE","COFFS HARBOUR","ROSELANDS","ORANGE","LISMORE","HAMMONDVILLE","BOWRAL","DUBBO","GRAFTON","NOWRA","ERINA","WOLLONGONG","DEE WHY","YASS","WOY WOY","WALLSEND","MOREE","MERRYLANDS","HORNSBY","ROSEBERY","CABRAMATTA","PARRAMATTA","LIVERPOOL","WAGGA WAGGA","HORNINGSEA PARK","BANKSTOWN","PADDINGTON","BONDI JUNCTION","LINDFIELD","WAHROONGA","NEWCASTLE","BALLINA","GLEBE","MAITLAND","CORRIMAL","CAMDEN","CASTLE HILL","REGENTS PARK","GRIFFITH","TORONTO","TWEED HEADS SOUTH","SEVEN HILLS","BLACKTOWN","GLADESVILLE","SMITHFIELD","TAHMOOR","SPRINGWOOD","FIVE DOCK","NEUTRAL BAY","EPPING","MUSWELLBROOK","CARINGBAH","THE ENTRANCE","MONA VALE","WEST KEMPSEY","MARRICKVILLE","BATHURST","ARMIDALE","BONDI JUNCTION","KIAMA","SHELLHARBOUR","WYONG","BROKEN HILL","ROUSE HILL","PORT MACQUARIE","FAIRFIELD");

foreach($hoge as $v){
    echo "SELECT * FROM `locations` WHERE suburb LIKE '%$v%';"."<br />";
}
