<?php
class Politicians extends CakeMigration {

/**
 * Migration description
 *
 * @var string
 * @access public
 */
	public $description = '';

/**
 * Actions to be performed
 *
 * @var array $migration
 * @access public
 */
	public $migration = array(
		'up' => array(
			'create_table' => array(
				'politicians' => array(
					'id' => array('type' => 'integer', 'null' => false, 'length' => 10, 'key' => 'primary'),
                                        'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2),
					'initials' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 6, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'user_id'),
					'surname' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 12, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'initials'),
					'title' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 8, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'surname'),
					'post-nominals' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 40, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'title'),
					'salutation' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 15, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'post-nominals'),
					'party' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 22, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'salutation'),
					'electorate' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 19, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'party'),
					'ministry' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 119, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'electorate'),
					'contact_address_line1' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 34, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministry'),
					'contact_address_line2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 42, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_line1'),
					'contact_address_line3' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 19, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_line2'),
					'contact_address_suburb' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 17, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_line3'),
					'contact_address_state' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 3, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_suburb'),
					'contact_address_postcode' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 4, 'after' => 'contact_address_state'),
					'contact_address_pobox_' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 11, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_postcode'),
					'contact_address_pobox_suburb' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 12, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_pobox_'),
					'contact_address_pobox_state' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 3, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_pobox_suburb'),
					'contact_address_pobox_postcode' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 4, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_pobox_state'),
					'contact_address_email' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 48, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_pobox_postcode'),
					'contact_address_phone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 14, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_email'),
					'contact_address_fax' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 14, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_phone'),
					'contact_address_website' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_fax'),
					'ministerial_office_address_line1' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 33, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'contact_address_website'),
					'ministerial_office_address_line2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 16, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_address_line1'),
					'ministerial_office_address_line3' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 16, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_address_line2'),
					'ministerial_office_address_suburb' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_address_line3'),
					'ministerial_office_address_state' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 3, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_address_suburb'),
					'ministerial_office_address_postcode' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 4, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_address_state'),
					'ministerial_office_pobox_' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 12, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_address_postcode'),
					'ministerial_office_pobox_suburb' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 6, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_pobox_'),
					'ministerial_office_pobox_state' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 3, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_pobox_suburb'),
					'ministerial_office_pobox_postcode' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 4, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_pobox_state'),
					'ministerial_office_email' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 39, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_pobox_postcode'),
					'ministerial_office_phone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 14, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_email'),
					'ministerial_office_fax' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 14, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_phone'),
					'ministerial_office_website' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_fax'),
					'alternative_office_address_line1' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 16, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'ministerial_office_website'),
					'alternative_office_address_line2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_address_line1'),
					'alternative_office_address_line3' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_address_line2'),
					'alternative_office_address_suburb' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 5, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_address_line3'),
					'alternative_office_address_state' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 3, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_address_suburb'),
					'alternative_office_address_postcode' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 4, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_address_state'),
					'alternative_office_pobox_' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_address_postcode'),
					'alternative_office_pobox_suburb' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_pobox_'),
					'alternative_office_pobox_state' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_pobox_suburb'),
					'alternative_office_pobox_postcode' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_pobox_state'),
					'alternative_office_email' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 42, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_pobox_postcode'),
					'alternative_office_phone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 14, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_email'),
					'alternative_office_fax' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 14, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_phone'),
					'alternative_office_website' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_fax'),
					'office_holder' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 23, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'alternative_office_website'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
			),
		),
		'down' => array(
			'drop_table' => array(
				'politicians'
			),
		),
	);

/**
 * Before migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 * @access public
 */
	public function before($direction) {
		return true;
	}

/**
 * After migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 * @access public
 */
	public function after($direction) {

        if ($direction == 'up') {
                $this->Location = ClassRegistry::init('Location');
                $this->Location->query("
INSERT INTO `politicians` (`id`, `user_id`, `initials`, `surname`, `title`, `post-nominals`, `salutation`, `party`, `electorate`, `ministry`, `contact_address_line1`, `contact_address_line2`, `contact_address_line3`, `contact_address_suburb`, `contact_address_state`, `contact_address_postcode`, `contact_address_pobox_`, `contact_address_pobox_suburb`, `contact_address_pobox_state`, `contact_address_pobox_postcode`, `contact_address_email`, `contact_address_phone`, `contact_address_fax`, `contact_address_website`, `ministerial_office_address_line1`, `ministerial_office_address_line2`, `ministerial_office_address_line3`, `ministerial_office_address_suburb`, `ministerial_office_address_state`, `ministerial_office_address_postcode`, `ministerial_office_pobox_`, `ministerial_office_pobox_suburb`, `ministerial_office_pobox_state`, `ministerial_office_pobox_postcode`, `ministerial_office_email`, `ministerial_office_phone`, `ministerial_office_fax`, `ministerial_office_website`, `alternative_office_address_line1`, `alternative_office_address_line2`, `alternative_office_address_line3`, `alternative_office_address_suburb`, `alternative_office_address_state`, `alternative_office_address_postcode`, `alternative_office_pobox_`, `alternative_office_pobox_suburb`, `alternative_office_pobox_state`, `alternative_office_pobox_postcode`, `alternative_office_email`, `alternative_office_phone`, `alternative_office_fax`, `alternative_office_website`, `office_holder`) VALUES
(1, 1, 'R.S.', 'Amery', 'The Hon.', 'M.P.', 'Mr Amery', 'Australian Labor Party', 'Mount Druitt', '', 'Suite 208', 'Westfield Shoppingtown', 'Carlisle Avenue', 'MOUNT DRUITT', 'NSW', 2770, '', '', '', '', 'mountdruitt@parliament.nsw.gov.au', '(02) 9625 6770', '(02) 9625 9965', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Opposition Whip'),
(2, 2, 'K.J.', 'Anderson', 'Mr', 'M.P.', 'Mr Anderson', 'The Nationals', 'Tamworth', '', 'Ground Floor', '13 Fitzroy Street', '', 'TAMWORTH', 'NSW', 2340, '', '', '', '', 'tamworth@parliament.nsw.gov.au', '(02) 6766 1422', '(02) 6766 6765', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(3, 3, 'G.', 'Annesley', 'The Hon.', 'M.P.', 'Minister', 'Liberal Party', 'Miranda', 'Minister for Sport and Recreation', '577 Kingsway', '', '', 'MIRANDA', 'NSW', 2228, '', '', '', '', 'miranda@parliament.nsw.gov.au', '(02) 9525 6378', '(02) 9540 2517', '', 'Level 33 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@annesley.minister.nsw.gov.au', '(02) 9228 5259', '(02) 9228 5727', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(4, 4, 'G.J.', 'Aplin', 'Mr', 'M.P. BA(Hons)', 'Mr Aplin', 'Liberal Party', 'Albury', '', '612 Dean Street', '', '', 'ALBURY', 'NSW', 2640, '', '', '', '', 'albury@parliament.nsw.gov.au', '(02) 6021 3042', '(02) 6021 8884', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(5, 5, 'S.L.', 'Ayres', 'Mr', 'M.P.', 'Mr Ayres', 'Liberal Party', 'Penrith', '', 'Shop 23 Ground Floor', 'Penrith Centre', '510-534 High Street', 'PENRITH', 'NSW', 2750, '', '', '', '', 'penrith@parliament.nsw.gov.au', '4722 8660', '4731 4782', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Deputy Government Whip'),
(6, 6, 'M.B.', 'Baird', 'The Hon.', 'M.P.', 'Minister', 'Liberal Party', 'Manly', 'Treasurer', 'Shop 2', '2 Wentworth Street', '', 'MANLY', 'NSW', 2095, '', '', '', '', 'manly@parliament.nsw.gov.au', '(02) 9976 2773', '(02) 9976 2993', '', 'Level 36 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@treasurer.nsw.gov.au', '(02) 9228 5274', '(02) 9228 3942', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(7, 7, 'G.D.', 'Barilaro', 'Mr', 'M.P.', 'Mr Barilaro', 'The Nationals', 'Monaro', '', '110-112 Monaro Street', '', '', 'QUEANBEYAN', 'NSW', 2620, '', '', '', '', 'monaro@parliament.nsw.gov.au', '(02) 6299 4899', '(02) 6297 9998', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Acting Speaker'),
(8, 8, 'C.G.', 'Barr', 'Mr', 'M.P. BEd', 'Mr Barr', 'Australian Labor Party', 'Cessnock', '', '118 Vincent Street', '', '', 'CESSNOCK', 'NSW', 2325, 'PO Box 242', 'Cessnock', 'NSW', '2325', 'cessnock@parliament.nsw.gov.au', '(02) 4991 1466', '(02) 4991 1103', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(9, 9, 'B.E.', 'Bassett', 'Mr', 'M.P.', 'Mr Bassett', 'Liberal Party', 'Londonderry', '', 'Shop 12', '82 Victoria Street', '', 'WERRINGTON', 'NSW', 2747, '', '', '', '', 'londonderry@parliament.nsw.gov.au', '(02) 9833 1122', '(02) 9623 1185', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(10, 10, 'C.A.', 'Baumann', 'Mr', 'M.P. BE(Civil)(Hons) FIEAust', 'Mr Baumann', 'Liberal Party', 'Port Stephens', '', '1/82 Port Stephens Street', '', '', 'RAYMOND TERRACE', 'NSW', 2324, '', '', '', '', 'portstephens@parliament.nsw.gov.au', '(02) 4987 4455', '(02) 4987 4466', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Parliamentary Secretary'),
(11, 11, 'G.', 'Berejiklian', 'The Hon.', 'M.P. BA DIntS MCom', 'Minister', 'Liberal Party', 'Willoughby', 'Minister for Transport', '280 Willoughby Road', '', '', 'NAREMBURN', 'NSW', 2065, '', '', '', '', 'willoughby@parliament.nsw.gov.au', '(02) 9439 4199', '(02) 9439 9299', '', 'Level 35 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@berejiklian.minister.nsw.gov.au', '(02) 9228 5266', '(02) 9228 3744', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(12, 12, 'S.B.', 'Bromhead', 'Mr', 'M.P. LLM', 'Mr Bromhead', 'The Nationals', 'Myall Lakes', '', 'Room F6 Bridgepoint Building', 'Lot 1-5 Manning Street', '', 'TUNCURRY', 'NSW', 2428, '', '', '', '', 'myalllakes@parliament.nsw.gov.au', '(02) 6555 4099', '(02) 6555 4780', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(13, 13, 'G.E.', 'Brookes', 'Mr', 'M.P.', 'Mr Brookes', 'Liberal Party', 'East Hills', '', '20 Revesby Place', '', '', 'REVESBY', 'NSW', 2212, '', '', '', '', 'easthills@parliament.nsw.gov.au', '(02) 9772 2774', '(02) 9792 1718', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(14, 14, 'L.J.', 'Burney', 'The Hon.', 'M.P. HonDEd DipEd', 'Ms Burney', 'Australian Labor Party', 'Canterbury', '', 'Suites 201 & 202 Level 2', '308-312 Beamish Street', '', 'CAMPSIE', 'NSW', 2194, '', '', '', '', 'linda.burney@parliament.nsw.gov.au', '(02) 9718 1234', '(02) 9787 1999', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(15, 15, 'C.A.', 'Burton', 'Ms', 'M.P.', 'Ms Burton', 'Australian Labor Party', 'Kogarah', '', 'Suite 1 Ground Floor', '22-24 Regent Street', '', 'KOGARAH', 'NSW', 2217, '', '', '', '', 'kogarah@parliament.nsw.gov.au', '(02) 9587 9684', '(02) 9588 7138', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(16, 16, 'C.', 'Casuscelli', 'Mr', 'M.P. RFD', 'Mr Casuscelli', 'Liberal Party', 'Strathfield', '', 'Shop 1', '54 Burwood Road', '', 'BURWOOD', 'NSW', 2134, '', '', '', '', 'strathfield@parliament.nsw.gov.au', '(02) 9747 1711', '(02) 9747 6054', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(17, 17, 'K.F.', 'Conolly', 'Mr', 'M.P. BA DipEd GradDipRS GradDipEd', 'Mr Conolly', 'Liberal Party', 'Riverstone', '', 'Shop 20 Stanhope Village', '2 Sentry Drive', '', 'STANHOPE GARDENS', 'NSW', 2768, '', '', '', '', 'riverstone@parliament.nsw.gov.au', '(02) 8883 3499', '(02) 8883 3355', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(18, 18, 'A.J.', 'Constance', 'The Hon.', 'M.P.', 'Minister', 'Liberal Party', 'Bega', 'Minister for Ageing; and Minister for Disability Services', '122 Carp Street', '', '', 'BEGA', 'NSW', 2550, '', '', '', '', 'bega@parliament.nsw.gov.au', '(02) 6492 2056', '(02) 6492 3578', '', 'Level 34 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@constance.minister.nsw.gov.au', '(02) 9228 5263', '(02) 9228 5500', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(19, 19, 'A.S.', 'Cornwell', 'Mr', 'M.P.', 'Mr Cornwell', 'Liberal Party', 'Charlestown', '', 'Suite 4 Level 2 The Forum Complex', '240 - 244 Pacific Highway', '', 'CHARLESTOWN', 'NSW', 2290, '', '', '', '', 'charlestown@parliament.nsw.gov.au', '(02) 4942 1242', '(02) 4942 1060', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(20, 20, 'M.J.', 'Coure', 'Mr', 'M.P.', 'Mr Coure', 'Liberal Party', 'Oatley', '', '8 Ormonde Parade', '', '', 'HURSTVILLE', 'NSW', 2220, '', '', '', '', 'oatley@parliament.nsw.gov.au', '(02) 9580 9349', '(02) 9580 9103', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(21, 21, 'M.J.', 'Daley', 'Mr', 'M.P. DipLaw', 'Mr Daley', 'Australian Labor Party', 'Maroubra', '', 'Level 5', '806 Anzac Parade', '', 'MAROUBRA', 'NSW', 2035, '', '', '', '', 'maroubra@parliament.nsw.gov.au', '(02) 9349 6440', '(02) 9349 4594', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(22, 22, 'T.', 'Davies', 'Mrs', 'M.P. BAppSc(Phty)', 'Mrs Davies', 'Liberal Party', 'Mulgoa', '', 'Shop 1', '159 Queen Street', '', 'ST MARYS', 'NSW', 2760, 'PO Box 138', 'St Marys', 'NSW', '2760', 'mulgoa@parliament.nsw.gov.au', '(02) 9833 2913', '(02) 9833 4063', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(23, 23, 'V.M.', 'Dominello', 'The Hon.', 'M.P.', 'Minister', 'Liberal Party', 'Ryde', 'Minister for Citizenship and Communities; and Minister for Aboriginal Affairs', 'Suite 202 Ground Floor', '5-9 Devlin Street', '', 'RYDE', 'NSW', 2112, '', '', '', '', 'ryde@parliament.nsw.gov.au', '(02) 9808 3288', '(02) 9877 6222', '', 'Level 37 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@dominello.minister.nsw.gov.au', '(02) 9228 4333', '(02) 9228 4392', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(24, 24, 'B.M.', 'Doyle', 'Mr', 'M.P. MBA GCMGT LLB', 'Mr Doyle', 'Liberal Party', 'Campbelltown', '', 'Suite 2A', '263 Queen Street', '', 'CAMPBELLTOWN', 'NSW', 2560, '', '', '', '', 'campbelltown@parliament.nsw.gov.au', '(02) 4625 3344', '(02) 4626 3640', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(25, 25, 'G.K.', 'Edwards', 'Mr', 'M.P.', 'Mr Edwards', 'Liberal Party', 'Swansea', '', 'Shop 1', '204-206 Pacific Highway', '', 'SWANSEA', 'NSW', 2281, '', '', '', '', 'swansea@parliament.nsw.gov.au', '(02) 4972 1133', '(02) 4972 1494', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(26, 26, 'D.A.', 'Elliott', 'Mr', 'M.P. BA MA', 'Mr Elliott', 'Liberal Party', 'Baulkham Hills', '', 'Suite 1', '25-33 Old Northern Road', '', 'BAULKHAM HILLS', 'NSW', 2153, '', '', '', '', 'baulkhamhills@parliament.nsw.gov.au', '(02) 9686 3110', '(02) 9686 3212', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(27, 27, 'L.J.', 'Evans', 'Mr', 'M.P.', 'Mr Evans', 'Liberal Party', 'Heathcote', '', 'Shops 1 & 2', '17 - 23 Station Street', '', 'ENGADINE', 'NSW', 2233, '', '', '', '', 'heathcote@parliament.nsw.gov.au', '(02) 9548 0144', '(02) 9548 5639', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Acting Speaker'),
(28, 28, 'J.F.', 'Flowers', 'Mr', 'M.P.', 'Mr Flowers', 'Liberal Party', 'Rockdale', '', '478 Princes Highway', '', '', 'ROCKDALE', 'NSW', 2216, '', '', '', '', 'rockdale@parliament.nsw.gov.au', '(02) 9597 1414', '(02) 9567 0508', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(29, 29, 'A.R.G.', 'Fraser', 'Mr', 'M.P.', 'Mr Fraser', 'The Nationals', 'Coffs Harbour', '', '1/9 Park Avenue', '', '', 'COFFS HARBOUR', 'NSW', 2450, '', '', '', '', 'coffsharbour@parliament.nsw.gov.au', '(02) 6652 6500', '(02) 6652 7934', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Assistant Speaker'),
(30, 30, 'R.A.', 'Furolo', 'Mr', 'M.P.', 'Mr Furolo', 'Australian Labor Party', 'Lakemba', '', 'Shop F081', 'Roselands Shopping Centre', 'Roselands Drive', 'ROSELANDS', 'NSW', 2196, 'PO Box 5', 'ROSELANDS', 'NSW', '2196', 'lakemba@parliament.nsw.gov.au', '(02) 9759 5000', '(02) 9759 1945', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(31, 31, 'A.R.', 'Gee', 'Mr', 'M.P. BEc(Hons) LLB', 'Mr Gee', 'The Nationals', 'Orange', '', '123 Byng Street', '', '', 'ORANGE', 'NSW', 2800, '', '', '', '', 'orange@parliament.nsw.gov.au', '(02) 6362 5199', '(02) 6361 3922', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(32, 32, 'T.', 'George', 'The Hon.', 'M.P.', 'The Hon. George', 'The Nationals', 'Lismore', '', '55 Carrington Street', '', '', 'LISMORE', 'NSW', 2480, 'PO Box 52', 'Lismore', 'NSW', '2480', 'lismore@parliament.nsw.gov.au', '(02) 6621 3624', '(02) 6622 1403', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Deputy Speaker'),
(33, 33, 'M.R.', 'Gibbons', 'Ms', 'M.P.', 'Ms Gibbons', 'Liberal Party', 'Menai', '', '60 Walder Road', '', '', 'HAMMONDVILLE', 'NSW', 2170, '', '', '', '', 'menai@parliament.nsw.gov.au', '(02) 9825 3653', '(02) 9825 4861', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Acting Speaker'),
(34, 34, 'P.J.', 'Goward', 'The Hon.', 'M.P.', 'Minister', 'Liberal Party', 'Goulburn', 'Minister for Family and Community Services; and Minister for Women', '288 Bong Bong Street', '', '', 'BOWRAL', 'NSW', 2576, '', '', '', '', 'goulburn@parliament.nsw.gov.au', '(02) 4861 3623', '(02) 4861 3546', '', 'Level 34 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@goward.minister.nsw.gov.au', '(02) 9228 5413', '(02) 9228 5501', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(35, 35, 'T.W.', 'Grant', 'Mr', 'M.P.', 'Mr Grant', 'The Nationals', 'Dubbo', '', 'Shop 1', '18 Talbragar Street', '', 'DUBBO', 'NSW', 2830, '', '', '', '', 'dubbo@parliament.nsw.gov.au', '(02) 6882 3577', '(02) 6882 3689', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Parliamentary Secretary'),
(36, 36, 'C.', 'Gulaptis', 'Mr', 'M.P.', 'Mr Gulaptis', 'The Nationals', 'Clarence', '', '11 Prince Street', '', '', 'GRAFTON', 'NSW', 2460, '', '', '', '', 'clarence@parliament.nsw.gov.au', '(02) 6643 1244', '(02) 6642 7574', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(37, 37, 'S.E.', 'Hancock', 'The Hon.', 'M.P. BA DipEd', 'Mrs Hancock', 'Liberal Party', 'South Coast', '', 'Ground Floor', '38 Berry Street', '', 'NOWRA', 'NSW', 2541, '', '', '', '', 'southcoast@parliament.nsw.gov.au', '(02) 4421 0222', '(02) 4422 1180', '', 'Parliament of New South Wales', 'Macquarie Street', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'speaker@parliament.nsw.gov.au', '(02) 9230 2201', '(02) 9230 2846', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Speaker'),
(38, 38, 'C.P.', 'Hartcher', 'The Hon.', 'M.P.', 'Minister', 'Liberal Party', 'Terrigal', 'Minister for Resources and Energy; Special Minister of State; and Minister for the Central Coast', 'Shop 3 Fountain Plaza', '148-158 The Entrance Road', '', 'ERINA', 'NSW', 2250, '', '', '', '', 'terrigal@parliament.nsw.gov.au', '(02) 4365 1906', '(02) 4365 4768', '', 'Level 37 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@hartcher.minister.nsw.gov.au', '(02) 9228 5289', '(02) 9228 3448', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(39, 39, 'N.', 'Hay', 'Ms', 'M.P.', 'Ms Hay', 'Australian Labor Party', 'Wollongong', '', 'Suite 2S Rear Ground Floor', '111 Crown Street', '', 'WOLLONGONG', 'NSW', 2500, '', '', '', '', 'wollongong@parliament.nsw.gov.au', '(02) 4226 5700', '(02) 4226 9963', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(40, 40, 'B.R.', 'Hazzard', 'The Hon.', 'M.P. BA DipEd LLB(NSW) LLM(Syd)', 'Minister', 'Liberal Party', 'Wakehurst', 'Minister for Planning and Infrastructure; and Minister Assisting the Premier on Infrastructure NSW; Leader of the House', 'Shop 3 637-641 Pittwater Road', '', '', 'DEE WHY', 'NSW', 2099, 'P O Box 405', 'DEE WHY', 'NSW', '2099', 'wakehurst@parliament.nsw.gov.au', '(02) 9981 1111', '(02) 9981 5059', '', 'Level 31 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@hazzard.minister.nsw.gov.au', '(02) 9228 5258', '(02) 9228 5721', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(41, 41, 'K.A.', 'Hodgkinson', 'The Hon.', 'M.P.', 'Minister', 'The Nationals', 'Burrinjuck', 'Minister for Primary Industries; and Minister for Small Business', '133 Comur Street', '', '', 'YASS', 'NSW', 2582, '', '', '', '', 'burrinjuck@parliament.nsw.gov.au', '(02) 6226 3311', '(02) 6226 3345', '', 'Level 30 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@hodgkinson.minister.nsw.gov.au ', '(02) 9228 5210', '(02) 9228 5969', '', '', '', '', '', '', '', '', '', '', '', 'invitations@hodgkinson.minister.nsw.gov.au', '', '', '', ''),
(42, 42, 'C.D.', 'Holstein', 'Mr', 'M.P.', 'Mr Holstein', 'Liberal Party', 'Gosford', '', '20 Blackwall Road', '', '', 'WOY WOY', 'NSW', 2256, '', '', '', '', 'gosford@parliament.nsw.gov.au', '(02) 4342 4122', '(02) 4341 2368', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(43, 43, 'S.K.', 'Hornery', 'Ms', 'M.P. JP BA(Hist)(Hons)', 'Ms Hornery', 'Australian Labor Party', 'Wallsend', '', 'Suite 3 30 Dan Rees Street', '', '', 'WALLSEND', 'NSW', 2287, 'PO Box 324', 'WALLSEND', 'NSW', '2287', 'wallsend@parliament.nsw.gov.au', '(02) 4950 0955', '(02) 4950 0977', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Acting Speaker'),
(44, 44, 'K.J.', 'Humphries', 'The Hon.', 'M.P.', 'Minister', 'The Nationals', 'Barwon', 'Minister for Mental Health; Minister for Healthy Lifestyles; and Minister for Western New South Wales', 'Suites 2-6', '161 Balo Street', '', 'MOREE', 'NSW', 2400, '', '', '', '', 'barwon@parliament.nsw.gov.au', '(02) 6752 5002', '(02) 6752 6102', '', 'Level 31 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@humphries.minister.nsw.gov.au', '(02) 9228 5248', '(02) 9228 5882', '', '11 Barton Street', '', '', 'COBAR', 'NSW', '2835', '', '', '', '', '', '(02) 6836 3722', '(02) 6836 3811', '', ''),
(45, 45, 'A.', 'Issa', 'Mr', 'M.P. OAM', 'Mr Issa', 'Liberal Party', 'Granville', '', '160 Merrylands Road', '', '', 'MERRYLANDS', 'NSW', 2160, '', '', '', '', 'granville@parliament.nsw.gov.au', '(02) 9637 1656', '(02) 9897 1434', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(46, 46, 'M.J.', 'Kean', 'Mr', 'M.P. BBus GradDipCA', 'Mr Kean', 'Liberal Party', 'Hornsby', '', 'Suite 5 The Madison', '25-29 Hunter Street', '', 'HORNSBY', 'NSW', 2077, '', '', '', '', 'hornsby@parliament.nsw.gov.au', '(02) 9476 3411', '(02) 9476 2965', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(47, 47, 'K.K.', 'Keneally', 'The Hon.', 'M.P.', 'Ms Keneally', 'Australian Labor Party', 'Heffron', '', 'Shop 117', '747 Botany Road', '', 'ROSEBERY', 'NSW', 2018, '', '', '', '', 'heffron@parliament.nsw.gov.au', '(02) 9699 8166', '(02) 9699 8222', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(48, 48, 'N.', 'Lalich', 'Mr', 'M.P.', 'Mr Lalich', 'Australian Labor Party', 'Cabramatta', '', 'Suite 10 Level 1', '5 Arthur Street', '', 'CABRAMATTA', 'NSW', 2166, '', '', '', '', 'cabramatta@parliament.nsw.gov.au', '(02) 9724 3381', '(02) 9724 6056', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(49, 49, 'G.', 'Lee', 'Dr', 'M.P. BAppSc(Hort) MBA DBA', 'Dr Lee', 'Liberal Party', 'Parramatta', '', '90 George Street', '', '', 'PARRAMATTA', 'NSW', 2150, '', '', '', '', 'parramatta@parliament.nsw.gov.au', '(02) 9891 4722', '(02) 9891 5618', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(50, 50, 'P.G.', 'Lynch', 'The Hon.', 'M.P.', 'Mr Lynch', 'Australian Labor Party', 'Liverpool', '', '100 Moore Street', '', '', 'LIVERPOOL', 'NSW', 2170, '', '', '', '', 'ElectorateOffice.Liverpool@parliament.nsw.gov.au', '(02) 9602 0040', '(02) 9821 1807', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(51, 51, 'D.W.', 'Maguire', 'Mr', 'M.P.', 'Mr Maguire', 'Liberal Party', 'Wagga Wagga', '', '76 Morgan Street', '', '', 'WAGGA WAGGA', 'NSW', 2650, '', '', '', '', 'waggawagga@parliament.nsw.gov.au', '(02) 6921 1622', '(02) 6921 4424', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Government Whip'),
(52, 52, 'A.D.', 'McDonald', 'Dr', 'M.P. MBBS(Hons) FRACP FRCP(Glasg) FRCPCH', 'Dr McDonald', 'Australian Labor Party', 'Macquarie Fields', '', 'Shop 18 Carnes Hill Marketplace', 'Corner Cowpasture & Kurrajong Roads', '', 'HORNINGSEA PARK', 'NSW', 2171, '', '', '', '', 'macquariefields@parliament.nsw.gov.au', '(02) 9608 8991', '(02) 9608 0606', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(53, 53, 'M.', 'Mihailuk', 'Ms', 'M.P. BEc LLB', 'Ms Mihailuk', 'Australian Labor Party', 'Bankstown', '', 'Suite 1 3rd Floor', '402-410 Chapel Road', '', 'BANKSTOWN', 'NSW', 2200, '', '', '', '', 'bankstown@parliament.nsw.gov.au', '(02) 9708 3838', '(02) 9708 3960', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(54, 54, 'C.', 'Moore', 'Ms', 'M.P.', 'Ms Moore', 'Independent', 'Sydney', '', '58 Oxford Street', '', '', 'PADDINGTON', 'NSW', 2021, '', '', '', '', 'sydney@parliament.nsw.gov.au', '(02) 9360 3053', '(02) 9331 6963', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(55, 55, 'B.N.', 'Notley-Smith', 'Mr', 'M.P.', 'Mr Notley-Smith', 'Liberal Party', 'Coogee', '', '80 Bronte Road', '', '', 'BONDI JUNCTION', 'NSW', 2022, '', '', '', '', 'coogee@parliament.nsw.gov.au', '(02) 9389 6669', '(02) 9387 8845', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(56, 56, 'J.R.', 'O''Dea', 'Mr', 'M.P. BA LLM MBA', 'Mr O''Dea', 'Liberal Party', 'Davidson', '', 'Suite 8A', '12 Tryon Road', '', 'LINDFIELD', 'NSW', 2070, '', '', '', '', 'davidson@parliament.nsw.gov.au', '(02) 9880 7400', '(02) 9880 7488', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(57, 57, 'B.R.', 'O''Farrell', 'The Hon.', 'M.P.', 'Premier', 'Liberal Party', 'Ku-ring-gai', 'Premier; and Minister for Western Sydney', '27 Redleaf Avenue', '', '', 'WAHROONGA', 'NSW', 2076, '', '', '', '', 'kuringgai@parliament.nsw.gov.au', '(02) 9487 8588', '(02) 9487 8550', '', 'Level 40 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', 'GPO Box 5341', 'SYDNEY', 'NSW', '2001', 'office@premier.nsw.gov.au', '9228 5239', '9228 3935', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(58, 58, 'T.F.', 'Owen', 'Mr', 'M.P. AM MSS', 'Mr Owen', 'Liberal Party', 'Newcastle', '', 'Ground Floor', '414 Hunter Street', '', 'NEWCASTLE', 'NSW', 2300, 'PO Box 1816', 'Newcastle', 'NSW', '2300', 'newcastle@parliament.nsw.gov.au', '(02) 4926 1126', '(02) 4926 2134', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(59, 59, 'D.L.', 'Page', 'The Hon.', 'M.P. BEc MEc DipRurAcctg', 'Minister', 'The Nationals', 'Ballina', 'Minister for Local Government; and Minister for the North Coast', 'Shop 1', '7 Moon Street', '', 'BALLINA', 'NSW', 2478, 'PO Box 1018', 'BALLINA', 'NSW', '2478', 'ballina@parliament.nsw.gov.au', '(02) 6686 7522', '(02) 6686 7470', '', 'Level 33 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@page.minister.nsw.gov.au', '(02) 9228 3403', '(02) 9228 3442', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(60, 60, 'J.T.', 'Parker', 'Mr', 'M.P.', 'Mr Parker', 'The Greens', 'Balmain', '', '112A Glebe Point Road', '', '', 'GLEBE', 'NSW', 2037, '', '', '', '', 'balmain@parliament.nsw.gov.au', '(02) 9660 7586', '(02) 9660 6112', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(61, 61, 'R. M.', 'Parker', 'The Hon.', 'M.P.', 'Minister', 'Liberal Party', 'Maitland', 'Minister for the Environment; and Minister for Heritage', '34 Church Street', '', '', 'MAITLAND', 'NSW', 2320, 'PO Box 920', 'MAITLAND', 'NSW', '2320', 'Robyn.Parker@parliament.nsw.gov.au', '(02) 4933 1617', '(02) 4933 4782', '', 'Level 32 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@parker.minister.nsw.gov.au', '(02) 9228 5253', '(02) 9228 5763', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(62, 62, 'R.J.', 'Park', 'Mr', 'M.P. BEd (Hons) MEd', 'Mr Park', 'Australian Labor Party', 'Keira', '', 'Shops 2 and 3', '247 Princes Highway', '', 'CORRIMAL', 'NSW', 2518, '', '', '', '', 'keira@parliament.nsw.gov.au', '(02) 4285 1588', '(02) 4285 1858', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(63, 63, 'C.', 'Patterson', 'Mr', 'M.P.', 'Mr Patterson', 'Liberal Party', 'Camden', '', '66 John Street', '', '', 'CAMDEN', 'NSW', 2570, '', '', '', '', 'camden@parliament.nsw.gov.au', '(02) 4655 3333', '(02) 4655 3325', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(64, 64, 'D.F.', 'Perrottet', 'Mr', 'M.P. LLB BCOM', 'Mr Perrottet', 'Liberal Party', 'Castle Hill', '', 'Suite 11', '2-4 Old Castle Hill Road', '', 'CASTLE HILL', 'NSW', 2154, '', '', '', '', 'castlehill@parliament.nsw.gov.au', '(02) 9634 7474', '(02) 9899 3340', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(65, 65, 'B.M.', 'Perry', 'The Hon.', 'M.P. BA LLB', 'Mrs Perry', 'Australian Labor Party', 'Auburn', '', '54-58 Amy Street', '', '', 'REGENTS PARK', 'NSW', 2143, '', '', '', '', 'auburn@parliament.nsw.gov.au', '(02) 9644 6972', '(02) 9644 8290', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(66, 66, 'A.', 'Piccoli', 'The Hon.', 'M.P. BEc LLB', 'Minister', 'The Nationals', 'Murrumbidgee', 'Minister for Education', 'NSW Government Offices', '104-110 Banna Avenue', '', 'GRIFFITH', 'NSW', 2680, '', '', '', '', 'murrumbidgee@parliament.nsw.gov.au', '(02) 6962 6644', '(02) 6962 7725', '', 'Level 34 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@piccoli.minister.nsw.gov.au', '(02) 9228 5261', '(02) 9228 5492', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(67, 67, 'G.M.', 'Piper', 'Mr', 'M.P.', 'Mr Piper', 'Independent', 'Lake Macquarie', '', '92 Victory Parade', '', '', 'TORONTO', 'NSW', 2283, '', '', '', '', 'lakemacquarie@parliament.nsw.gov.au', '(02) 4959 3200', '(02) 4950 4076', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(68, 68, 'G.K.', 'Provest', 'Mr', 'M.P. CCM FAIM AICD JP', 'Mr Provest', 'The Nationals', 'Tweed', '', '103 Minjungbal Drive', '', '', 'TWEED HEADS SOUTH', 'NSW', 2486, '', '', '', '', 'tweed@parliament.nsw.gov.au', '(07) 5523 4816', '(07) 5523 4817', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Parliamentary Secretary'),
(69, 69, 'N.', 'Rees', 'The Hon.', 'M.P.', 'Mr Rees', 'Australian Labor Party', 'Toongabbie', '', '166 Best Road', '', '', 'SEVEN HILLS', 'NSW', 2147, '', '', '', '', 'toongabbie@parliament.nsw.gov.au', '(02) 9831 8022', '(02) 9831 8044', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(70, 70, 'J.', 'Robertson', 'Mr', 'M.P.', 'Mr Robertson', 'Australian Labor Party', 'Blacktown', '', 'Shop 3063', 'Westpoint Shopping Centre', 'Flushcombe Road', 'BLACKTOWN', 'NSW', 2148, '', '', '', '', 'blacktown@parliament.nsw.gov.au', '(02) 9671 5222', '(02) 9671 5266', '', 'Parliament House', 'Macquarie Street', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'leader.opposition@parliament.nsw.gov.au', '(02) 9230 2310', '(02) 9230 3355', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(71, 71, 'A.J.', 'Roberts', 'The Hon.', 'M.P. MA (Comms)', 'Minister', 'Liberal Party', 'Lane Cove', 'Minister for Fair Trading', 'Level 3 Suite 302', '230 Victoria Road', '', 'GLADESVILLE', 'NSW', 2111, '', '', '', '', 'lanecove@parliament.nsw.gov.au', '(02) 9817 4757', '(02) 9817 5885', '', 'Level 36 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@roberts.minister.nsw.gov.au', '(02) 9228 5276', '(02) 9228 4236', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(72, 72, 'A.R.', 'Rohan', 'Mr', 'M.P. BSc(Geology) MSc(Petroleum Geology)', 'Mr Rohan', 'Liberal Party', 'Smithfield', '', '2/679 The Horsley Drive', '', '', 'SMITHFIELD', 'NSW', 2164, '', '', '', '', 'smithfield@parliament.nsw.gov.au', '(02) 9756 4766', '(02) 9756 1544', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(73, 73, 'J.T.', 'Rowell', 'Mr', 'M.P.', 'Mr Rowell', 'Liberal Party', 'Wollondilly', '', 'Shop 1', '117 Remembrance Drive', '', 'TAHMOOR', 'NSW', 2573, '', '', '', '', 'wollondilly@parliament.nsw.gov.au', '(02) 4683 2622', '(02) 4683 2595', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(74, 74, 'R.E.M.', 'Sage', 'Mrs', 'M.P. BDSc', 'Mrs Sage', 'Liberal Party', 'Blue Mountains', '', '132 Macquarie Road', '', '', 'SPRINGWOOD', 'NSW', 2777, '', '', '', '', 'bluemountains@parliament.nsw.gov.au', '(02) 4751 3298', '(02) 4751 1245', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(75, 75, 'A.J.', 'Sidoti', 'Mr', 'M.P.', 'Mr Sidoti', 'Liberal Party', 'Drummoyne', '', '128 Great North Road', '', '', 'FIVE DOCK', 'NSW', 2046, '', '', '', '', 'drummoyne@parliament.nsw.gov.au', '(02) 9713 2999', '(02) 9713 2911', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(76, 76, 'J.G.', 'Skinner', 'The Hon.', 'M.P.', 'Minister', 'Liberal Party', 'North Shore', 'Minister for Health; and Minister for Medical Research', 'Suite 3', '40 Yeo Street', '', 'NEUTRAL BAY', 'NSW', 2089, '', '', '', '', 'northshore@parliament.nsw.gov.au', '(02) 9909 2594', '(02) 9909 2654', '', 'Level 31 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@skinner.minister.nsw.gov.au', '(02) 9228 5229', '(02) 9228 5877', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(77, 77, 'G.E.', 'Smith', 'The Hon.', 'M.P. SC', 'Minister', 'Liberal Party', 'Epping', 'Attorney General; and Minister for Justice', 'Suite 303', 'Level 3 51 Rawson Street', '', 'EPPING', 'NSW', 2121, '', '', '', '', 'epping@parliament.nsw.gov.au', '(02) 9877 0266', '(02) 9877 0405', '', 'Level 31 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@smith.minister.nsw.gov.au', '(02) 9228 5246', '(02) 9228 5874', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(78, 78, 'G.', 'Souris', 'The Hon.', 'M.P. BEc DipFMgt FAIM FCPA', 'Minister', 'The Nationals', 'Upper Hunter', 'Minister for Tourism Major Events Hospitality and Racing; and Minister for the Arts', '20 Bridge Street', '', '', 'MUSWELLBROOK', 'NSW', 2333, '', '', '', '', 'upperhunter@parliament.nsw.gov.au', '(02) 6543 1065', '(02) 6543 1416', '', 'Level 30 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@souris.minister.nsw.gov.au', '(02) 9228 5218', '(02) 9228 5968', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(79, 79, 'M.R.', 'Speakman', 'Mr', 'M.P. SC', 'Mr Speakman', 'Liberal Party', 'Cronulla', '', 'Shops 3 and 3A', '347-357 Port Hacking Road South', '', 'CARINGBAH', 'NSW', 2229, '', '', '', '', 'cronulla@parliament.nsw.gov.au', '(02) 9526 8377', '(02) 9526 8928', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(80, 80, 'C.E.', 'Spence', 'Mr', 'M.P.', 'Mr Spence', 'Liberal Party', 'The Entrance', '', '24 The Entrance Road', '', '', 'THE ENTRANCE', 'NSW', 2261, 'PO Box 401', 'The Entrance', 'NSW', '2261', 'TheEntrance@parliament.nsw.gov.au', '(02) 4334 1012', '(02) 4334 3840', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(81, 81, 'R.G.', 'Stokes', 'Mr', 'M.P.', 'Mr Stokes', 'Liberal Party', 'Pittwater', '', '1725 Pittwater Road', '', '', 'MONA VALE', 'NSW', 2103, '', '', '', '', 'pittwater@parliament.nsw.gov.au', '(02) 9999 3599', '(02) 9999 0922', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Parliamentary Secretary'),
(82, 82, 'A.J.', 'Stoner', 'The Hon.', 'M.P. BBus MBA', 'Minister', 'The Nationals', 'Oxley', 'Deputy Premier; Minister for Trade and Investment; and Minister for Regional Infrastructure and Services', '37 Elbow Street', '', '', 'WEST KEMPSEY', 'NSW', 2440, 'PO Box 3120', 'WEST KEMPSEY', 'NSW', '2440', 'oxley@parliament.nsw.gov.au', '(02) 6562 6190', '(02) 6563 1355', '', 'Level 30 Governor Macquarie Tower', '1 Farrer Place', '', 'SYDNEY', 'NSW', '2000', '', '', '', '', 'office@deputypremier.nsw.gov.au', '(02) 9228 5209', '(02) 9228 5970', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(83, 83, 'C.M.', 'Tebbutt', 'The Hon.', 'M.P. BEc', 'Ms Tebbutt', 'Australian Labor Party', 'Marrickville', '', '244 Illawarra Road', '', '', 'MARRICKVILLE', 'NSW', 2204, '', '', '', '', 'marrickville@parliament.nsw.gov.au', '(02) 9558 9000', '(02) 9558 3653', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(84, 84, 'P.L.', 'Toole', 'Mr', 'M.P. DipTeach', 'Mr Toole', 'The Nationals', 'Bathurst', '', 'Suites 1 and 2', '229 Howick Street', '', 'BATHURST', 'NSW', 2795, '', '', '', '', 'paul.toole@parliament.nsw.gov.au', '(02) 6332 1300', '(02) 6332 1900', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Parliamentary Secretary'),
(85, 85, 'G.R.', 'Torbay', 'The Hon.', 'M.P.', 'Mr Torbay', 'Independent', 'Northern Tablelands', '', 'Suite 1 Ground Floor', '175 Rusden Street', '', 'ARMIDALE', 'NSW', 2350, 'PO Box 77', 'ARMIDALE', 'NSW', '2350', 'northerntablelands@parliament.nsw.gov.au', '(02) 6772 5552', '(02) 6772 5026', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(86, 86, 'G.C.', 'Upton', 'Ms', 'M.P. MBA BA LLB', 'Ms Upton', 'Liberal Party', 'Vaucluse', '', 'Suite 102 332-342 Oxford Street', '', '', 'BONDI JUNCTION', 'NSW', 2022, '', '', '', '', 'vaucluse@parliament.nsw.gov.au', '(02) 9369 3017', '(02) 9389 8050', '', '', '', 'Macquarie Street', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Parliamentary Secretary'),
(87, 87, 'G.J.', 'Ward', 'Mr', 'M.P. BA BCom MAICD JP', 'Mr Ward', 'Liberal Party', 'Kiama', '', 'Terralong House', '125 Terralong Street', '', 'KIAMA', 'NSW', 2533, '', '', '', '', 'kiama@parliament.nsw.gov.au', '(02) 4232 1082', '(02) 4232 3577', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Acting Speaker'),
(88, 88, 'A.', 'Watson', 'Ms', 'M.P.', 'Ms Watson', 'Australian Labor Party', 'Shellharbour', '', 'Shop 3', '10 College Avenue Shellharbour City Centre', '', 'SHELLHARBOUR', 'NSW', 2529, '', '', '', '', 'shellharbour@parliament.nsw.gov.au', '(02) 4297 3111', '(02) 4297 3144', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(89, 89, 'D.J.', 'Webber', 'Mr', 'M.P.', 'Mr Webber', 'Liberal Party', 'Wyong', '', 'Shop 4', '142 Pacific Highway', '', 'WYONG', 'NSW', 2259, '', '', '', '', 'wyong@parliament.nsw.gov.au', '(02) 4352 2711', '(02) 4352 2766', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(90, 90, 'J.D.', 'Williams', 'Mr', 'M.P.', 'Mr Williams', 'The Nationals', 'Murray-Darling', '', '1/142 Argent St', '', '', 'BROKEN HILL', 'NSW', 2880, '', '', '', '', 'murraydarling@parliament.nsw.gov.au', '(08) 8087 3315', '(08) 8087 1796', '', '228 Cressy Street', '', '', 'Deniliquin', 'NSW', '2710', '', '', '', '', '', '(03) 5881 7034', '(03) 5881 7839', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'The Nationals Whip'),
(91, 91, 'R.C.', 'Williams', 'Mr', 'M.P.', 'Mr Williams', 'Liberal Party', 'Hawkesbury', '', 'Suite 202 Rouse Hill Town Centre', '10-14 Market Lane', '', 'ROUSE HILL', 'NSW', 2155, '', '', '', '', 'hawkesbury@parliament.nsw.gov.au', '(02) 8882 9555', '(02) 8882 9411', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Parliamentary Secretary'),
(92, 92, 'L.G.', 'Williams', 'Mrs', 'M.P. BNurs DipTeach', 'Mrs Williams', 'The Nationals', 'Port Macquarie', '', 'Suite 6', '27 Grant Street', '', 'PORT MACQUARIE', 'NSW', 2444, '', '', '', '', 'portmacquarie@parliament.nsw.gov.au', '(02) 6584 0977', '(02) 6584 0978', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(93, 93, 'G.', 'Zangari', 'Mr', 'M.P. BEd', 'Mr Zangari', 'Australian Labor Party', 'Fairfield', '', 'Suite 6 Neeta City Shopping Centre', 'Smart Street', '', 'FAIRFIELD', 'NSW', 2165, '', '', '', '', 'fairfield@parliament.nsw.gov.au', '(02) 9726 9323', '(02) 9726 9783', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
                    ");
        }
		return true;
	}
}
